auto: true

markdown: rdiscount
highlighter: true
paginate: 8
gems: [jekyll-paginate]
permalink: /:title

title: konglx90
url: http://konglx90.github.io/
feed: /atom.xml
author_info: <a href="http://konglx90.github.io//">konglx90</a>
