auto: true

markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
permalink: /:title

title: konglx90
url: https://konglx90.github.io/
feed: /atom.xml
author_info: <a href="https://konglx90.github.io/">konglx90</a>
